# Generated by Django 5.2.7 on 2025-12-01 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='bsiaw_regis_ip_addr_aef6c1_idx'), models.Index(fields=['timestamp'], name='bsiaw_regis_timesta_e8b939_idx')],
            },
        ),
    ]
